on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: yarn --dev && yarn build