name: checks
on:
  pull_request:

  push:
    branches:
      - main

jobs:
  check:
    name: build/lint/test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test --coverage

