on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: yarn install && yarn run test --coverage
